SELECT * FROM Stores;
SELECT * FROM Item;
SELECT * FROM Soldier;
SELECT * FROM Storeman;
SELECT * FROM Supplier;
SELECT * FROM Weapon;
SELECT * FROM Uniform;
SELECT * FROM Owns;
SELECT * FROM Supplies; 
