INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'New York', 1);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Medtronic', 'medtronic@example.com', 'Chicago', 2);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@business.com', 'San Diego', 3);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'San Jose', 4);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@example.com', 'Dallas', 5);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UnionPacific', 'unionpacific@company.com', 'Dallas', 6);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@mail.com', 'Chicago', 7);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amazon', 'amazon@business.com', 'San Jose', 8);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Altria', 'altria@example.com', 'San Antonio', 9);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Champion', 'champion@business.com', 'San Jose', 10);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('MolsonCoors', 'molsoncoors@mail.com', 'San Jose', 11);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Disney', 'disney@mail.com', 'Houston', 12);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PayPal', 'paypal@example.com', 'San Antonio', 13);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@example.com', 'Los Angeles', 14);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@company.com', 'New York', 15);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Corning', 'corning@example.com', 'Los Angeles', 16);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('TractorSupply', 'tractorsupply@business.com', 'Houston', 17);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@example.com', 'San Antonio', 18);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Roots', 'roots@mail.com', 'Dallas', 19);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Salesforce', 'salesforce@mail.com', 'Phoenix', 20);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Champion', 'champion@example.com', 'San Jose', 21);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tesla', 'tesla@business.com', 'Houston', 22);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Organigram', 'organigram@mail.com', 'New York', 23);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@company.com', 'Dallas', 24);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CuraleafHoldings', 'curaleafholdings@business.com', 'San Jose', 25);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Facebook', 'facebook@company.com', 'Philadelphia', 26);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NVIDIA', 'nvidia@example.com', 'San Antonio', 27);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Nike', 'nike@business.com', 'Chicago', 28);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Paccar', 'paccar@business.com', 'San Jose', 29);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@mail.com', 'Philadelphia', 30);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Salesforce', 'salesforce@company.com', 'Phoenix', 31);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Enbridge', 'enbridge@business.com', 'Houston', 32);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gucci', 'gucci@example.com', 'Los Angeles', 33);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@example.com', 'San Diego', 34);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Internationa', 'internationa@example.com', 'San Jose', 35);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@example.com', 'San Jose', 36);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Paccar', 'paccar@company.com', 'Philadelphia', 37);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UPS', 'ups@company.com', 'New York', 38);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Altria', 'altria@business.com', 'San Diego', 39);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@mail.com', 'Los Angeles', 40);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Apple', 'apple@mail.com', 'San Antonio', 41);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NorthFace', 'northface@business.com', 'New York', 42);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Roots', 'roots@company.com', 'New York', 43);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Starbucks', 'starbucks@mail.com', 'San Jose', 44);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Citigroup', 'citigroup@business.com', 'San Antonio', 45);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Broadcom', 'broadcom@example.com', 'Houston', 46);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('WeedMD', 'weedmd@business.com', 'Phoenix', 47);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@company.com', 'San Antonio', 48);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gucci', 'gucci@example.com', 'Phoenix', 49);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chewy', 'chewy@business.com', 'Philadelphia', 50);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@company.com', 'San Jose', 51);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Corning', 'corning@business.com', 'San Antonio', 52);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Manulife', 'manulife@company.com', 'Chicago', 53);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Oracle', 'oracle@company.com', 'Houston', 54);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UnionPacific', 'unionpacific@company.com', 'New York', 55);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CuraleafHoldings', 'curaleafholdings@company.com', 'Phoenix', 56);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BigLots', 'biglots@company.com', 'San Jose', 57);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanadianTire', 'canadiantire@business.com', 'San Jose', 58);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UnionPacific', 'unionpacific@mail.com', 'Chicago', 59);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Ford', 'ford@mail.com', 'San Diego', 60);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Aflac', 'aflac@mail.com', 'San Jose', 61);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@example.com', 'Chicago', 62);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UnionPacific', 'unionpacific@business.com', 'San Antonio', 63);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Microsoft', 'microsoft@example.com', 'San Diego', 64);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Google', 'google@company.com', 'San Diego', 65);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@business.com', 'San Diego', 66);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tilray', 'tilray@mail.com', 'Chicago', 67);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Target', 'target@mail.com', 'Dallas', 68);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Apple', 'apple@company.com', 'Philadelphia', 69);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BooksAMillion', 'booksamillion@example.com', 'New York', 70);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BlackBerry', 'blackberry@example.com', 'New York', 71);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CrescoLabs', 'crescolabs@business.com', 'San Diego', 72);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@mail.com', 'San Antonio', 73);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('TractorSupply', 'tractorsupply@example.com', 'Dallas', 74);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Intel', 'intel@company.com', 'San Antonio', 75);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@business.com', 'Los Angeles', 76);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BarnesNoble', 'barnesnoble@mail.com', 'Houston', 77);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PublicStorage', 'publicstorage@example.com', 'Philadelphia', 78);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Nordion', 'nordion@company.com', 'Dallas', 79);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@example.com', 'San Antonio', 80);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Broadcom', 'broadcom@mail.com', 'Philadelphia', 81);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Aflac', 'aflac@example.com', 'New York', 82);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amazon', 'amazon@business.com', 'San Antonio', 83);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@business.com', 'Houston', 84);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Halliburton', 'halliburton@company.com', 'Chicago', 85);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HibbettSports', 'hibbettsports@business.com', 'San Antonio', 86);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Intel', 'intel@business.com', 'New York', 87);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@example.com', 'San Antonio', 88);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@mail.com', 'New York', 89);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NorthFace', 'northface@company.com', 'San Jose', 90);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Honeywell', 'honeywell@mail.com', 'San Antonio', 91);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BarrickGold', 'barrickgold@example.com', 'San Diego', 92);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@mail.com', 'Chicago', 93);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@example.com', 'Houston', 94);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanopyGrowth', 'canopygrowth@company.com', 'San Antonio', 95);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@mail.com', 'New York', 96);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@business.com', 'Dallas', 97);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@company.com', 'New York', 98);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NorthFace', 'northface@business.com', 'New York', 99);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fossil', 'fossil@example.com', 'Los Angeles', 100);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Caterpillar', 'caterpillar@mail.com', 'Phoenix', 101);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@mail.com', 'San Antonio', 102);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Target', 'target@company.com', 'New York', 103);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@mail.com', 'Philadelphia', 104);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Nordion', 'nordion@example.com', 'San Diego', 105);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@mail.com', 'Dallas', 106);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chewy', 'chewy@company.com', 'Chicago', 107);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'Houston', 108);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@company.com', 'New York', 109);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Internationa', 'internationa@business.com', 'San Jose', 110);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@example.com', 'New York', 111);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BigLots', 'biglots@business.com', 'San Antonio', 112);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BostonProperties', 'bostonproperties@company.com', 'Philadelphia', 113);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@mail.com', 'Philadelphia', 114);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CrescoLabs', 'crescolabs@mail.com', 'Phoenix', 115);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ImperialOil', 'imperialoil@mail.com', 'San Jose', 116);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hexo', 'hexo@example.com', 'Chicago', 117);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Organigram', 'organigram@example.com', 'San Antonio', 118);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Target', 'target@example.com', 'San Antonio', 119);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@mail.com', 'San Diego', 120);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@example.com', 'Los Angeles', 121);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@mail.com', 'Phoenix', 122);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Corning', 'corning@business.com', 'San Diego', 123);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Manulife', 'manulife@business.com', 'Los Angeles', 124);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OnexCorporation', 'onexcorporation@example.com', 'San Jose', 125);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hermes', 'hermes@company.com', 'Phoenix', 126);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('TractorSupply', 'tractorsupply@company.com', 'San Antonio', 127);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Humana', 'humana@company.com', 'San Jose', 128);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('SpinMaster', 'spinmaster@company.com', 'Dallas', 129);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PayPal', 'paypal@mail.com', 'San Jose', 130);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BigLots', 'biglots@business.com', 'Houston', 131);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Cisco', 'cisco@example.com', 'Los Angeles', 132);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PartyCity', 'partycity@company.com', 'San Jose', 133);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tesla', 'tesla@company.com', 'New York', 134);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanopyGrowth', 'canopygrowth@mail.com', 'Houston', 135);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@example.com', 'Phoenix', 136);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Google', 'google@example.com', 'Los Angeles', 137);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@company.com', 'San Antonio', 138);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Mastercard', 'mastercard@example.com', 'Chicago', 139);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanadianTire', 'canadiantire@business.com', 'New York', 140);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OnexCorporation', 'onexcorporation@business.com', 'Chicago', 141);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('MolsonCoors', 'molsoncoors@company.com', 'Los Angeles', 142);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Roots', 'roots@mail.com', 'Houston', 143);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanadianTire', 'canadiantire@business.com', 'Houston', 144);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fossil', 'fossil@company.com', 'San Antonio', 145);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BestBuy', 'bestbuy@business.com', 'Dallas', 146);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Telus', 'telus@mail.com', 'Houston', 147);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Altria', 'altria@company.com', 'San Jose', 148);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Walmart', 'walmart@mail.com', 'Phoenix', 149);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Enbridge', 'enbridge@business.com', 'Houston', 150);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('J.Crew', 'j.crew@business.com', 'New York', 151);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Paccar', 'paccar@business.com', 'Houston', 152);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@mail.com', 'Los Angeles', 153);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Facebook', 'facebook@company.com', 'Chicago', 154);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@company.com', 'New York', 155);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@business.com', 'Houston', 156);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hermes', 'hermes@company.com', 'Philadelphia', 157);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Target', 'target@mail.com', 'Houston', 158);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Telus', 'telus@business.com', 'Houston', 159);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@mail.com', 'Chicago', 160);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NorthFace', 'northface@mail.com', 'Houston', 161);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@mail.com', 'San Diego', 162);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Paccar', 'paccar@business.com', 'New York', 163);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@mail.com', 'Houston', 164);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Roots', 'roots@example.com', 'Dallas', 165);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@mail.com', 'Los Angeles', 166);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@mail.com', 'Los Angeles', 167);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Ford', 'ford@company.com', 'Chicago', 168);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PayPal', 'paypal@company.com', 'Dallas', 169);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Cameco', 'cameco@mail.com', 'San Diego', 170);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Google', 'google@company.com', 'Los Angeles', 171);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Corning', 'corning@company.com', 'Philadelphia', 172);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@mail.com', 'Los Angeles', 173);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Medtronic', 'medtronic@business.com', 'Chicago', 174);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GoldmanSachs', 'goldmansachs@company.com', 'Phoenix', 175);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@business.com', 'Los Angeles', 176);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BigLots', 'biglots@example.com', 'Los Angeles', 177);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gucci', 'gucci@company.com', 'Houston', 178);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Intel', 'intel@company.com', 'New York', 179);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('SpinMaster', 'spinmaster@mail.com', 'Dallas', 180);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@mail.com', 'Dallas', 181);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@company.com', 'San Diego', 182);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Nordion', 'nordion@example.com', 'Dallas', 183);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Humana', 'humana@mail.com', 'Dallas', 184);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('VF', 'vf@example.com', 'Phoenix', 185);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gucci', 'gucci@company.com', 'Chicago', 186);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@company.com', 'San Antonio', 187);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Aflac', 'aflac@example.com', 'Phoenix', 188);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@example.com', 'San Antonio', 189);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('WeedMD', 'weedmd@business.com', 'Houston', 190);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Caterpillar', 'caterpillar@business.com', 'Phoenix', 191);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Internationa', 'internationa@mail.com', 'Chicago', 192);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chevron', 'chevron@company.com', 'San Jose', 193);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@company.com', 'Dallas', 194);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Disney', 'disney@company.com', 'Houston', 195);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HibbettSports', 'hibbettsports@mail.com', 'San Diego', 196);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PublicStorage', 'publicstorage@mail.com', 'New York', 197);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Enbridge', 'enbridge@example.com', 'Los Angeles', 198);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amazon', 'amazon@example.com', 'Los Angeles', 199);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Cisco', 'cisco@example.com', 'Houston', 200);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ExxonMobil', 'exxonmobil@business.com', 'New York', 201);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Visa', 'visa@example.com', 'Dallas', 202);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Humana', 'humana@example.com', 'San Jose', 203);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@example.com', 'Dallas', 204);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HarborFreightTools', 'harborfreighttools@example.com', 'Chicago', 205);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@example.com', 'Philadelphia', 206);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BigLots', 'biglots@business.com', 'Los Angeles', 207);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tilray', 'tilray@mail.com', 'Phoenix', 208);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ExxonMobil', 'exxonmobil@company.com', 'Houston', 209);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@business.com', 'Philadelphia', 210);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chevron', 'chevron@business.com', 'New York', 211);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@business.com', 'Philadelphia', 212);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@mail.com', 'San Diego', 213);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HarborFreightTools', 'harborfreighttools@mail.com', 'Chicago', 214);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AmericanEagle', 'americaneagle@company.com', 'Houston', 215);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@example.com', 'New York', 216);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CuraleafHoldings', 'curaleafholdings@mail.com', 'Los Angeles', 217);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@mail.com', 'San Antonio', 218);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@example.com', 'Los Angeles', 219);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@mail.com', 'Los Angeles', 220);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@mail.com', 'Chicago', 221);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hermes', 'hermes@company.com', 'Dallas', 222);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tilray', 'tilray@example.com', 'San Antonio', 223);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@business.com', 'Los Angeles', 224);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Disney', 'disney@example.com', 'Phoenix', 225);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HibbettSports', 'hibbettsports@example.com', 'San Jose', 226);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@mail.com', 'Chicago', 227);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Nordion', 'nordion@business.com', 'Los Angeles', 228);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BooksAMillion', 'booksamillion@example.com', 'Los Angeles', 229);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@business.com', 'San Antonio', 230);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@business.com', 'Dallas', 231);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fossil', 'fossil@business.com', 'Dallas', 232);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AmericanEagle', 'americaneagle@business.com', 'Los Angeles', 233);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@company.com', 'Philadelphia', 234);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HibbettSports', 'hibbettsports@company.com', 'Philadelphia', 235);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@company.com', 'Phoenix', 236);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('SpinMaster', 'spinmaster@mail.com', 'Philadelphia', 237);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@company.com', 'San Jose', 238);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Boeing', 'boeing@example.com', 'Chicago', 239);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@example.com', 'Los Angeles', 240);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@example.com', 'Chicago', 241);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UPS', 'ups@business.com', 'Chicago', 242);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PublicStorage', 'publicstorage@example.com', 'New York', 243);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UPS', 'ups@business.com', 'Chicago', 244);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PartyCity', 'partycity@company.com', 'Philadelphia', 245);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amazon', 'amazon@business.com', 'New York', 246);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@example.com', 'Houston', 247);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Cameco', 'cameco@example.com', 'Dallas', 248);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Petco', 'petco@company.com', 'New York', 249);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Altria', 'altria@company.com', 'Houston', 250);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@company.com', 'San Diego', 251);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Aflac', 'aflac@example.com', 'Phoenix', 252);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Cameco', 'cameco@business.com', 'San Antonio', 253);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Mastercard', 'mastercard@example.com', 'Philadelphia', 254);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@mail.com', 'Phoenix', 255);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PartyCity', 'partycity@company.com', 'Los Angeles', 256);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@example.com', 'Dallas', 257);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@mail.com', 'Chicago', 258);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Telus', 'telus@company.com', 'Chicago', 259);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amazon', 'amazon@company.com', 'Phoenix', 260);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Oracle', 'oracle@example.com', 'Phoenix', 261);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('MolsonCoors', 'molsoncoors@company.com', 'San Diego', 262);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ClarksShoes', 'clarksshoes@company.com', 'Phoenix', 263);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@business.com', 'New York', 264);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Walmart', 'walmart@company.com', 'Phoenix', 265);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('LundinMining', 'lundinmining@example.com', 'Houston', 266);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@company.com', 'Phoenix', 267);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@company.com', 'Los Angeles', 268);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@example.com', 'Los Angeles', 269);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Broadcom', 'broadcom@example.com', 'San Diego', 270);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@company.com', 'Houston', 271);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HarborFreightTools', 'harborfreighttools@mail.com', 'Houston', 272);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Manulife', 'manulife@example.com', 'Los Angeles', 273);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('VF', 'vf@mail.com', 'Dallas', 274);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('LundinMining', 'lundinmining@mail.com', 'Dallas', 275);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('J.Crew', 'j.crew@mail.com', 'New York', 276);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@company.com', 'San Antonio', 277);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ExxonMobil', 'exxonmobil@company.com', 'Los Angeles', 278);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@mail.com', 'Dallas', 279);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chevron', 'chevron@company.com', 'Los Angeles', 280);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('FootLocker', 'footlocker@business.com', 'Houston', 281);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('HibbettSports', 'hibbettsports@company.com', 'Houston', 282);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Mastercard', 'mastercard@business.com', 'New York', 283);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@mail.com', 'Dallas', 284);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('EmersonElectric', 'emersonelectric@company.com', 'San Diego', 285);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GoldmanSachs', 'goldmansachs@business.com', 'Los Angeles', 286);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@company.com', 'Houston', 287);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@example.com', 'San Antonio', 288);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hollister', 'hollister@mail.com', 'San Diego', 289);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Paccar', 'paccar@example.com', 'San Diego', 290);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Walmart', 'walmart@company.com', 'Philadelphia', 291);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Altria', 'altria@example.com', 'Los Angeles', 292);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Walmart', 'walmart@mail.com', 'New York', 293);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@mail.com', 'Houston', 294);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Halliburton', 'halliburton@mail.com', 'Dallas', 295);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@company.com', 'Dallas', 296);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@company.com', 'San Jose', 297);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@mail.com', 'San Antonio', 298);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Visa', 'visa@company.com', 'San Antonio', 299);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BooksAMillion', 'booksamillion@company.com', 'Chicago', 300);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Petco', 'petco@example.com', 'New York', 301);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CuraleafHoldings', 'curaleafholdings@company.com', 'Dallas', 302);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Qualcomm', 'qualcomm@mail.com', 'San Jose', 303);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BarrickGold', 'barrickgold@mail.com', 'Houston', 304);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Walmart', 'walmart@company.com', 'San Diego', 305);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Caterpillar', 'caterpillar@company.com', 'San Jose', 306);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chewy', 'chewy@company.com', 'Los Angeles', 307);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@example.com', 'Phoenix', 308);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'Houston', 309);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PayPal', 'paypal@business.com', 'Houston', 310);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gap', 'gap@example.com', 'Philadelphia', 311);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CanopyGrowth', 'canopygrowth@example.com', 'Los Angeles', 312);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Facebook', 'facebook@mail.com', 'San Jose', 313);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Corning', 'corning@example.com', 'San Antonio', 314);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Wrangler', 'wrangler@company.com', 'Houston', 315);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@example.com', 'New York', 316);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OReillyAutoParts', 'oreillyautoparts@company.com', 'Philadelphia', 317);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Costco', 'costco@example.com', 'Phoenix', 318);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('NVIDIA', 'nvidia@company.com', 'Philadelphia', 319);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Verizon', 'verizon@business.com', 'Dallas', 320);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'Phoenix', 321);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('J.Crew', 'j.crew@mail.com', 'Houston', 322);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prada', 'prada@mail.com', 'Houston', 323);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@example.com', 'San Diego', 324);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Dollarama', 'dollarama@business.com', 'Philadelphia', 325);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chevron', 'chevron@business.com', 'Houston', 326);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BlackBerry', 'blackberry@example.com', 'Houston', 327);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BostonProperties', 'bostonproperties@company.com', 'San Antonio', 328);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hollister', 'hollister@business.com', 'Los Angeles', 329);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@example.com', 'Los Angeles', 330);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Oracle', 'oracle@business.com', 'San Jose', 331);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('MedMenEnterprises', 'medmenenterprises@mail.com', 'Los Angeles', 332);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Timberland', 'timberland@example.com', 'San Antonio', 333);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@mail.com', 'Phoenix', 334);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@company.com', 'Phoenix', 335);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('TractorSupply', 'tractorsupply@business.com', 'New York', 336);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Aflac', 'aflac@mail.com', 'Los Angeles', 337);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tesla', 'tesla@example.com', 'Houston', 338);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('CuraleafHoldings', 'curaleafholdings@mail.com', 'Philadelphia', 339);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('PayPal', 'paypal@company.com', 'Houston', 340);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@example.com', 'Philadelphia', 341);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuxlyCannabisGroup', 'auxlycannabisgroup@company.com', 'San Antonio', 342);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('MedMenEnterprises', 'medmenenterprises@mail.com', 'Dallas', 343);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Champion', 'champion@example.com', 'San Antonio', 344);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Mastercard', 'mastercard@example.com', 'San Jose', 345);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@business.com', 'Philadelphia', 346);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('WeedMD', 'weedmd@business.com', 'Houston', 347);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Oracle', 'oracle@mail.com', 'San Jose', 348);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuroraCannabis', 'auroracannabis@company.com', 'San Jose', 349);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Pfizer', 'pfizer@company.com', 'Dallas', 350);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BarnesNoble', 'barnesnoble@company.com', 'Chicago', 351);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@mail.com', 'New York', 352);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BestBuy', 'bestbuy@mail.com', 'Houston', 353);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tilray', 'tilray@business.com', 'Chicago', 354);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Ford', 'ford@company.com', 'San Jose', 355);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BlackBerry', 'blackberry@mail.com', 'San Antonio', 356);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@example.com', 'Los Angeles', 357);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Telus', 'telus@mail.com', 'Houston', 358);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BooksAMillion', 'booksamillion@example.com', 'Phoenix', 359);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Enbridge', 'enbridge@example.com', 'Philadelphia', 360);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@company.com', 'San Diego', 361);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BestBuy', 'bestbuy@example.com', 'Los Angeles', 362);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@business.com', 'San Antonio', 363);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Disney', 'disney@mail.com', 'Chicago', 364);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@mail.com', 'San Jose', 365);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Hollister', 'hollister@company.com', 'Philadelphia', 366);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Disney', 'disney@business.com', 'New York', 367);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Microsoft', 'microsoft@mail.com', 'Philadelphia', 368);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@business.com', 'Philadelphia', 369);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('UnionPacific', 'unionpacific@company.com', 'Houston', 370);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Petco', 'petco@company.com', 'Philadelphia', 371);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Amgen', 'amgen@company.com', 'San Diego', 372);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Broadcom', 'broadcom@business.com', 'Philadelphia', 373);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('OpenText', 'opentext@business.com', 'Dallas', 374);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Chevron', 'chevron@mail.com', 'Los Angeles', 375);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Gucci', 'gucci@mail.com', 'Houston', 376);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Wrangler', 'wrangler@mail.com', 'San Diego', 377);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Prologis', 'prologis@business.com', 'San Antonio', 378);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BarrickGold', 'barrickgold@example.com', 'San Diego', 379);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fossil', 'fossil@business.com', 'San Jose', 380);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Boeing', 'boeing@business.com', 'Philadelphia', 381);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Bombardier', 'bombardier@company.com', 'Phoenix', 382);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Bombardier', 'bombardier@business.com', 'New York', 383);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('BestBuy', 'bestbuy@mail.com', 'Phoenix', 384);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@example.com', 'New York', 385);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('GameStop', 'gamestop@company.com', 'Philadelphia', 386);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Netflix', 'netflix@example.com', 'San Diego', 387);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('SpinMaster', 'spinmaster@example.com', 'Phoenix', 388);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Adobe', 'adobe@business.com', 'Dallas', 389);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Tilray', 'tilray@company.com', 'Philadelphia', 390);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Metro', 'metro@example.com', 'Chicago', 391);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AutoZone', 'autozone@mail.com', 'Phoenix', 392);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Fendi', 'fendi@business.com', 'Phoenix', 393);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Internationa', 'internationa@mail.com', 'New York', 394);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Facebook', 'facebook@business.com', 'Los Angeles', 395);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('AuxlyCannabisGroup', 'auxlycannabisgroup@example.com', 'Houston', 396);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Microsoft', 'microsoft@company.com', 'Chicago', 397);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('ClarksShoes', 'clarksshoes@mail.com', 'Phoenix', 398);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Halliburton', 'halliburton@mail.com', 'Dallas', 399);
INSERT INTO Supplier (Company_Name, Email, Location, Company_ID) VALUES ('Comcast', 'comcast@mail.com', 'New York', 400);
COMMIT;
